In [18]:
from sklearn.datasets import load_iris,load_breast_cancer,load_digits
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.model_selection import train_test_split,GridSearchCV
X, y = load_iris(return_X_y=True)
kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel,random_state=0).fit(X, y)
print(gpc.score(X, y))
gpc.predict_proba(X[:2,:])

0.9866666666666667


array([[0.83548752, 0.03228706, 0.13222543],
       [0.79064206, 0.06525643, 0.14410151]])

In [19]:
import numpy as np
import pandas as pd

In [20]:
from warnings import filterwarnings
filterwarnings('ignore')

In [23]:
X, y = load_breast_cancer(return_X_y=True)
kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel,random_state=0).fit(X, y)
print(gpc.score(X, y))
gpc.predict_proba(X[:2,:])

0.9595782073813708


array([[0.82897975, 0.17102025],
       [0.72388084, 0.27611916]])

In [24]:
X, y = load_digits(return_X_y=True)
kernel = 1.0 * RBF(1.0)
gpc = GaussianProcessClassifier(kernel=kernel,random_state=0).fit(X, y)
print(gpc.score(X, y))
gpc.predict_proba(X[:2,:])

1.0


array([[0.10000045, 0.09999995, 0.09999995, 0.09999995, 0.09999995,
        0.09999995, 0.09999995, 0.09999995, 0.09999995, 0.09999995],
       [0.09999995, 0.10000045, 0.09999995, 0.09999995, 0.09999995,
        0.09999995, 0.09999995, 0.09999995, 0.09999995, 0.09999995]])